/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/expenses': typeof ExpensesRoute
  '/invoices': typeof InvoicesRoute
  '/patients': typeof PatientsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/expenses': typeof ExpensesRoute
  '/invoices': typeof InvoicesRoute
  '/settings': typeof SettingsRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients': typeof PatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/expenses': typeof ExpensesRoute
  '/invoices': typeof InvoicesRoute
  '/patients': typeof PatientsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/expenses'
    | '/invoices'
    | '/patients'
    | '/settings'
    | '/patients/$id'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/expenses'
    | '/invoices'
    | '/settings'
    | '/patients/$id'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/expenses'
    | '/invoices'
    | '/patients'
    | '/settings'
    | '/patients/$id'
    | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  ExpensesRoute: typeof ExpensesRoute
  InvoicesRoute: typeof InvoicesRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof PatientsRoute
    }
  }
}

interface PatientsRouteChildren {
  PatientsIdRoute: typeof PatientsIdRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsIdRoute: PatientsIdRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  ExpensesRoute: ExpensesRoute,
  InvoicesRoute: InvoicesRoute,
  PatientsRoute: PatientsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
